import { z } from 'zod';

export const createEventSchema = z.object({
    body: z.object({
        title: z.string().min(3, 'Title must be at least 3 characters'),
        description: z.string().min(10, 'Description must be at least 10 characters'),
        shortDescription: z.string().max(200).optional(),
        eventType: z.enum(['IN_PERSON', 'VIRTUAL', 'HYBRID']),
        venue: z.string().optional(),
        address: z.string().optional(),
        city: z.string().optional(),
        country: z.string().optional(),
        latitude: z.number().min(-90).max(90).optional(),
        longitude: z.number().min(-180).max(180).optional(),
        startTime: z.string().datetime(),
        endTime: z.string().datetime(),
        timezone: z.string().default('UTC'),
        maxCapacity: z.number().positive().optional(),
        ticketSource: z.enum(['INTERNAL', 'AFFILIATE']).default('INTERNAL'),
        affiliateUrl: z.string().url().optional(),
        affiliateCode: z.string().optional(),
        isFree: z.boolean().default(false),
        basePrice: z.number().min(0).optional(),
        currency: z.string().default('USD'),
        tags: z.array(z.string()).optional(),
        categoryIds: z.array(z.string()).optional(),
        organizationId: z.string().optional(),
    }),
});

export const updateEventSchema = z.object({
    body: z.object({
        title: z.string().min(3).optional(),
        description: z.string().min(10).optional(),
        shortDescription: z.string().max(200).optional(),
        eventType: z.enum(['IN_PERSON', 'VIRTUAL', 'HYBRID']).optional(),
        status: z.enum(['DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED']).optional(),
        venue: z.string().optional(),
        address: z.string().optional(),
        city: z.string().optional(),
        country: z.string().optional(),
        latitude: z.number().min(-90).max(90).optional(),
        longitude: z.number().min(-180).max(180).optional(),
        startTime: z.string().datetime().optional(),
        endTime: z.string().datetime().optional(),
        timezone: z.string().optional(),
        maxCapacity: z.number().positive().optional(),
        ticketSource: z.enum(['INTERNAL', 'AFFILIATE']).optional(),
        affiliateUrl: z.string().url().optional(),
        affiliateCode: z.string().optional(),
        isFree: z.boolean().optional(),
        basePrice: z.number().min(0).optional(),
        currency: z.string().optional(),
        tags: z.array(z.string()).optional(),
        categoryIds: z.array(z.string()).optional(),
        featured: z.boolean().optional(),
    }),
});

export const searchEventsSchema = z.object({
    query: z.object({
        q: z.string().optional(),
        eventType: z.enum(['IN_PERSON', 'VIRTUAL', 'HYBRID']).optional(),
        city: z.string().optional(),
        country: z.string().optional(),
        startDate: z.string().datetime().optional(),
        endDate: z.string().datetime().optional(),
        isFree: z.string().optional(),
        minPrice: z.string().optional(),
        maxPrice: z.string().optional(),
        categoryId: z.string().optional(),
        tags: z.string().optional(),
        featured: z.string().optional(),
        latitude: z.string().optional(),
        longitude: z.string().optional(),
        radius: z.string().optional(),
        page: z.string().optional(),
        limit: z.string().optional(),
        sortBy: z.string().optional(),
    }),
});
